version: 1.0.0.0-alpha{build}

branches:

  only:

  - master

max_jobs: 15

image: Visual Studio 2019 Preview

configuration: Release

platform: Any CPU

dotnet_csproj:

  patch: true

  file: '**\*.csproj'

  version: '{version}'

  version_prefix: '{version}'

  package_version: '{version}'

  assembly_version: '{version}'

  file_version: '{version}'

  informational_version: '{version}'

build_script:

- ps: dotnet build --configuration Release

deploy:

- provider: NuGet

  api_key:

    secure: 07A4N3G5s1VV2v8AbDaGu+nYsZcw6o2hSx/f2I45ob4=

  on:

    APPVEYOR_REPO_TAG: true
